---
title: "R Notebook"
output: html_notebook
---




```{r}
#install.packages(c("jsonlite", "network", "ergm"))
library(jsonlite)
library(network)
library(ergm)
```

```{r}
#Read file & build network'
dat <- fromJSON("data/starwars-teams.json")

nodes <- dat$nodes
links <- dat$links

n_nodes <- nrow(nodes)

# undirected binary network
g <- network.initialize(n_nodes, directed = FALSE)

# node names
network.vertex.names(g) <- nodes$name

# node attributes
set.vertex.attribute(g, "team", nodes$team)
set.vertex.attribute(g, "value", nodes$value)
set.vertex.attribute(g, "colour", nodes$colour)

# links use 0-based indexing, so add 1 for R
add.edges(
  g,
  tail = links$source + 1,
  head = links$target + 1
)

#summary(g)
network.size(g)
network.edgecount(g)
```
```{r}
#Basic plot
plot(g,
     vertex.col = nodes$colour,
     vertex.cex = 0.6,
     displaylabels = FALSE)
```
```{r}
# Improved network plot

node_size <- 0.8 + 2.2 * (nodes$value - min(nodes$value)) /
  (max(nodes$value) - min(nodes$value))

show_labels <- nodes$value >= quantile(nodes$value, 0.8)
labels <- ifelse(show_labels, nodes$name, "")

set.seed(123)

par(mar = c(1,1,3,1), bg = "white")

plot(
  g,
  displaylabels = TRUE,
  label = labels,
  label.cex = 0.7,
  label.pos = 5,
  vertex.col = nodes$colour,
  vertex.cex = node_size,
  vertex.border = "gray20",
  edge.col = rgb(0,0,0,0.15),
  edge.lwd = 1.1,
  mode = "fruchtermanreingold",
  main = "Star Wars Character Network"
)
```


```{r}
#Fit ERGM
m1 <- ergm(g ~ edges)
summary(m1)
```
```{r}
#Edges between same team?
m2 <- ergm(g ~ edges + nodematch("team"))
summary(m2)
```
```{r}
#More edges if more scenes?
m3 <- ergm(g ~ edges + nodematch("team") + nodecov("value"))
summary(m3)
```
```{r}
m4 <- ergm(g ~ edges + nodematch("team") + nodecov("value") + gwdegree(0.25, fixed = TRUE))
summary(m4)
```


```{r}
m5 <- ergm(g ~ edges + nodematch("team") + nodecov("value") +
             gwdegree(0.25, fixed = TRUE) + gwdsp(0.5, fixed=TRUE) + gwesp(0.5, fixed = TRUE))
summary(m5)
```
```{r}
mcmc.diagnostics(m5)
```


```{r}
gof_m5 <- gof(m5)
plot(gof_m5)
```
```{r}
gof_m5 <- gof(m5 ~ degree + espartners + distance)
plot(gof_m5)
```

```{r}
#random graph check

# same number of nodes as your real network
n <- network.size(g)

# create random graph with similar density
p <- network.edgecount(g) / (n * (n - 1) / 2)

g_rand <- network.initialize(n, directed = FALSE)
g_rand <- simulate(g_rand ~ edges, coef = qlogis(p))

# copy attributes from original network
g_rand %v% "team" <- g %v% "team"
g_rand %v% "value" <- g %v% "value"

m5_rand <- ergm(g_rand ~ edges + nodematch("team") + nodecov("value") +
                  gwdegree(0.25, fixed = TRUE) +
                  gwdsp(0.5, fixed = TRUE) +
                  gwesp(0.5, fixed = TRUE))

summary(m5_rand)


```

```{r}


```

